//! Embeds the built web client into the binary.
//!
//! `crates/pi-cli/web/` is a vite + react + typescript project. Its
//! production build (`npm run build`, vite-plugin-singlefile) emits one
//! self-contained `web/dist/index.html` (JS + CSS inlined), which is checked
//! in so `cargo build` never requires node — release CI, cargo-install users,
//! and offline builders all get the committed artifact. This build script
//! turns `web/dist/` into an embedded asset table
//! (`path -> (mime, bytes)`) at `$OUT_DIR/web_assets.rs`.
//!
//! To rebuild the assets: `cd crates/pi-cli/web && npm install && npm run build`.

use std::{
    env,
    fmt,
    fs,
    io,
    path::{Path, PathBuf},
};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dist = manifest.join("web").join("dist");
    let files = match collect_files(&dist, &dist) {
        Ok(files) if files.is_empty() => panic!(
            "no web client assets found in {}: run `npm install && npm run build` inside crates/pi-cli/web \
             (the committed dist/ artifact is missing)",
            dist.display()
        ),
        Ok(files) => files,
        Err(err) => panic!(
            "failed to collect web client assets from {}: {err}\n\
             run `npm install && npm run build` inside crates/pi-cli/web and make sure the committed \
             dist/ artifact is present and complete",
            dist.display()
        ),
    };

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from crates/pi-cli/web/dist — do not edit.\n");
    generated.push_str("#[allow(clippy::all)]\n");
    generated.push_str("pub(crate) static FILES: &[(&str, &str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        generated.push_str(&format!(
            "    ({:?}, {:?}, include_bytes!({:?})),\n",
            rel,
            mime_for(rel),
            abs
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("web_assets.rs");
    fs::write(&out, generated).expect("write web assets module");
    println!("cargo:rerun-if-changed={}", dist.display());
}

/// Walks `dir` under `root` and returns every regular file as a
/// `(root-relative path, absolute path)` pair, deterministically sorted by the
/// relative path. Fails on the first unreadable directory/entry, file-type
/// error, or non-regular entry (symlinks included) instead of silently
/// producing a partial asset table.
fn collect_files(root: &Path, dir: &Path) -> Result<Vec<(String, PathBuf)>, CollectError> {
    let mut files = Vec::new();
    collect_files_into(root, dir, &mut files)?;
    files.sort_by_key(|(rel, _)| rel.clone());
    Ok(files)
}

fn collect_files_into(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, PathBuf)>,
) -> Result<(), CollectError> {
    let entries = fs::read_dir(dir)
        .map_err(|err| CollectError::new(root, dir, CollectErrorDetail::ReadDir(err)))?;
    for entry in entries {
        let entry = entry
            .map_err(|err| CollectError::new(root, dir, CollectErrorDetail::ReadEntry(err)))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|err| CollectError::new(root, &path, CollectErrorDetail::FileType(err)))?;
        if file_type.is_dir() {
            collect_files_into(root, &path, out)?;
        } else if file_type.is_symlink() {
            return Err(CollectError::new(
                root,
                &path,
                CollectErrorDetail::Unsupported("symbolic link"),
            ));
        } else if file_type.is_file() {
            out.push((rel_path(root, &path), path));
        } else {
            return Err(CollectError::new(
                root,
                &path,
                CollectErrorDetail::Unsupported("neither a regular file nor a directory"),
            ));
        }
    }
    Ok(())
}

/// Error raised while walking the web client asset directory.
#[derive(Debug)]
struct CollectError {
    /// Failing path, relative to the dist root ("." for the root itself).
    rel: String,
    detail: CollectErrorDetail,
}

#[derive(Debug)]
enum CollectErrorDetail {
    /// `fs::read_dir` failed for a directory.
    ReadDir(io::Error),
    /// Reading a single directory entry failed.
    ReadEntry(io::Error),
    /// Determining an entry's file type failed.
    FileType(io::Error),
    /// Entry exists but is neither a regular file nor a directory (for
    /// example a symlink, FIFO, socket, or device).
    Unsupported(&'static str),
}

impl CollectError {
    fn new(root: &Path, path: &Path, detail: CollectErrorDetail) -> Self {
        Self {
            rel: rel_path(root, path),
            detail,
        }
    }
}

/// Renders `path` relative to `root` with forward slashes; the root itself
/// renders as ".".
fn rel_path(root: &Path, path: &Path) -> String {
    let rel = path.strip_prefix(root).unwrap_or(path);
    let rel = rel.to_string_lossy().replace('\\', "/");
    if rel.is_empty() {
        ".".to_owned()
    } else {
        rel
    }
}

impl fmt::Display for CollectError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.detail {
            CollectErrorDetail::ReadDir(err) => {
                write!(f, "cannot read directory {rel:?}: {err}", rel = self.rel)
            }
            CollectErrorDetail::ReadEntry(err) => write!(
                f,
                "cannot read an entry of directory {rel:?}: {err}",
                rel = self.rel
            ),
            CollectErrorDetail::FileType(err) => {
                write!(f, "cannot determine the type of {rel:?}: {err}", rel = self.rel)
            }
            CollectErrorDetail::Unsupported(kind) => {
                write!(f, "unsupported entry {rel:?}: {kind}", rel = self.rel)
            }
        }
    }
}

fn mime_for(path: &str) -> &'static str {
    if path.ends_with(".html") {
        "text/html; charset=utf-8"
    } else if path.ends_with(".js") || path.ends_with(".mjs") {
        "text/javascript"
    } else if path.ends_with(".css") {
        "text/css"
    } else if path.ends_with(".svg") {
        "image/svg+xml"
    } else if path.ends_with(".png") {
        "image/png"
    } else if path.ends_with(".jpg") || path.ends_with(".jpeg") {
        "image/jpeg"
    } else if path.ends_with(".gif") {
        "image/gif"
    } else if path.ends_with(".webp") {
        "image/webp"
    } else if path.ends_with(".woff2") {
        "font/woff2"
    } else if path.ends_with(".map") {
        "application/json"
    } else {
        "application/octet-stream"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    /// Creates a unique scratch directory for one test.
    fn scratch(name: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock before unix epoch")
            .as_nanos();
        let dir = env::temp_dir().join(format!(
            "pi-cli-build-{name}-{}-{unique}",
            std::process::id()
        ));
        fs::create_dir_all(&dir).expect("create scratch dir");
        dir
    }

    /// Writes `(relative path, contents)` entries under `root`.
    fn write_tree(root: &Path, entries: &[(&str, &str)]) {
        for (rel, contents) in entries {
            let path = root.join(rel);
            fs::create_dir_all(path.parent().expect("entry has a parent"))
                .expect("create parent dirs");
            fs::write(path, contents).expect("write entry");
        }
    }

    fn cleanup(root: &Path) {
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn collects_regular_files_sorted_and_deterministic() {
        let root = scratch("collect");
        write_tree(
            &root,
            &[
                ("index.html", "<!doctype html>"),
                ("assets/app.js", "console.log(1)"),
                ("assets/styles.css", "body {}"),
                ("assets/img/logo.svg", "<svg />"),
                ("assets/img/nested/deep.bin", "binary"),
            ],
        );
        let files = collect_files(&root, &root).expect("collect should succeed");
        let rels: Vec<&str> = files.iter().map(|(rel, _)| rel.as_str()).collect();
        assert_eq!(
            rels,
            vec![
                "assets/app.js",
                "assets/img/logo.svg",
                "assets/img/nested/deep.bin",
                "assets/styles.css",
                "index.html",
            ]
        );
        // Every entry points at an existing regular file under the root, and
        // its stored path matches the relative key.
        for (rel, abs) in &files {
            assert!(abs.is_absolute());
            assert!(abs.starts_with(&root));
            assert!(fs::symlink_metadata(abs).expect("entry exists").is_file());
            assert_eq!(&rel_path(&root, abs), rel);
        }
        // Deterministic: independent walks agree.
        let again = collect_files(&root, &root).expect("collect again");
        assert_eq!(files, again);
        cleanup(&root);
    }

    #[test]
    fn missing_dist_root_is_reported() {
        let root = scratch("missing");
        cleanup(&root); // ensure the root does not exist
        let err = collect_files(&root, &root).expect_err("missing root must fail");
        assert_eq!(err.rel, ".");
        assert!(matches!(err.detail, CollectErrorDetail::ReadDir(_)));
        assert!(err.to_string().contains("cannot read directory"));
        cleanup(&root);
    }

    #[cfg(unix)]
    #[test]
    fn unreadable_directory_is_reported_with_relative_path() {
        use std::os::unix::fs::PermissionsExt;

        let root = scratch("unreadable");
        write_tree(&root, &[("index.html", "<!doctype html>")]);
        let secret = root.join("secret");
        fs::create_dir_all(&secret).expect("create secret dir");
        fs::write(secret.join("data.txt"), "x").expect("write secret file");
        fs::set_permissions(&secret, fs::Permissions::from_mode(0o000)).expect("chmod 000");
        let result = collect_files(&root, &root);
        // Restore permissions before asserting so cleanup always works.
        fs::set_permissions(&secret, fs::Permissions::from_mode(0o700)).expect("restore chmod");
        match result {
            Err(err) => {
                assert_eq!(err.rel, "secret");
                let CollectErrorDetail::ReadDir(io_err) = &err.detail else {
                    panic!("expected a read_dir error, got: {err}");
                };
                assert_eq!(io_err.kind(), io::ErrorKind::PermissionDenied);
                assert!(err.to_string().contains("\"secret\""));
            }
            Ok(_) => {
                // Permissions are not enforced (e.g. running as root or a
                // filesystem that ignores mode bits) — the platform cannot
                // exercise this case, so record and skip.
                eprintln!("note: unreadable-directory assertion skipped (permissions not enforced)");
            }
        }
        cleanup(&root);
    }

    #[cfg(unix)]
    #[test]
    fn symlinks_are_rejected() {
        use std::os::unix::fs::symlink;

        let root = scratch("symlink");
        write_tree(&root, &[("index.html", "<!doctype html>"), ("assets/app.js", "js")]);
        // Symlink to a regular file.
        symlink(root.join("index.html"), root.join("link.html")).expect("create file symlink");
        let err = collect_files(&root, &root).expect_err("file symlink must be rejected");
        assert_eq!(err.rel, "link.html");
        assert!(matches!(err.detail, CollectErrorDetail::Unsupported("symbolic link")));
        // Symlink to a directory must not be followed into.
        fs::remove_file(root.join("link.html")).expect("remove file symlink");
        symlink(root.join("assets"), root.join("link-dir")).expect("create dir symlink");
        let err = collect_files(&root, &root).expect_err("dir symlink must be rejected");
        assert_eq!(err.rel, "link-dir");
        assert!(matches!(err.detail, CollectErrorDetail::Unsupported("symbolic link")));
        cleanup(&root);
    }

    #[cfg(unix)]
    #[test]
    fn non_regular_files_are_rejected() {
        let root = scratch("fifo");
        write_tree(&root, &[("index.html", "<!doctype html>")]);
        let fifo = root.join("pipe");
        let made = std::process::Command::new("mkfifo")
            .arg(&fifo)
            .status()
            .map(|status| status.success())
            .unwrap_or(false);
        if !made {
            eprintln!("note: mkfifo unavailable; skipping non-regular-file assertion");
            cleanup(&root);
            return;
        }
        let err = collect_files(&root, &root).expect_err("fifo must be rejected");
        assert_eq!(err.rel, "pipe");
        assert!(matches!(
            err.detail,
            CollectErrorDetail::Unsupported("neither a regular file nor a directory")
        ));
        cleanup(&root);
    }
}
